language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - if ["$TRAVIS_BRANCH" = "master"]; then npm run build; fi
  - if ["$TRAVIS_BRANCH" = "staging"]; then env-cmd .env.staging npm run build; fi
deploy:
  - provider: surge
    skip_cleanup: true
    domain: https://studio.votoinformado2019.com
    project: ./build/
    on:
      branch: master
  - provider: surge
    skip_cleanup: true
    domain: vstudio-staging.surge.sh
    project: ./build/
    on:
      branch: staging
