language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - if ["$TRAVIS_BRANCH" = "master"] npm run build
  - if ["$TRAVIS_BRANCH" = "staging"] env-cmd .env.staging npm run build
deploy:
  - provider: surge
    skip_cleanup: true
    domain: https://studio.votoinformado2019.com
    project: ./build/
    on:
      branch: master
  - provider: surge
    skip_cleanup: true
    domain: vstudio-staging.surge.sh
    project: ./build/
    on:
      branch: staging
